Repository FCP-INDI/C-PAC, pull requests merged in 2021-04, with the labels that each got.

#1486 Use AFNI to compute DVARS
  CPAC/generate_motion_statistics/__init__.py
  CPAC/generate_motion_statistics/generate_motion_statistics.py
  CPAC/generate_motion_statistics/test/test_dvars.py
  dev/docker_data/required_afni_pkgs.txt
Labels: improvement

#1491 Fix/1.8.1 modularity fixes 1
  CPAC/anat_preproc/anat_preproc.py
  CPAC/func_preproc/func_preproc.py
  CPAC/nuisance/nuisance.py
  CPAC/pipeline/engine.py
  CPAC/pipeline/schema.py
  CPAC/registration/registration.py
  dev/docker_data/default_pipeline.yml
Labels: engine

#1498 👷 Include ABCD-HCP tests in combined coverage
  .circleci/config.yml
  CPAC/conftest.py
  dev/circleci_data/test_in_image.sh
Labels: devops, testing
