Repository FCP-INDI/C-PAC, pull requests merged in 2021-09, with the labels that each got.

#1555 🎨 DRY
  CPAC/network_centrality/network_centrality.py
Labels: improvement

#1554 Network Centrality weight options
  CPAC/network_centrality/network_centrality.py
  CPAC/network_centrality/pipeline.py
  CPAC/network_centrality/utils.py
  CPAC/pipeline/engine.py
  CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml
Labels: bug

#1562 👷 Push to Docker Hub from CircleCI
  .circleci/config.yml
  .circleci/main.yml
Labels: devops

#1564 🔊 Restore resource logging for linear plugin
  dev/docker_data/run.py
Labels: bug, testing

#1574 🐛 FIX: `KeyError: 'in_file'`
  CHANGELOG.md
  CPAC/pipeline/nipype_pipeline_engine/engine.py
Labels: bug, support
