Repository FCP-INDI/C-PAC, pull requests merged in 2021-11, with the labels that each got.

#1596 🥅 Handle just-in-time estimation exceptions
  .circleci/main.yml
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/nipype_pipeline_engine/engine.py
  CPAC/pipeline/plugins/__init__.py
  CPAC/pipeline/plugins/cpac_nipype_custom.py
  CPAC/pipeline/plugins/legacymultiproc.py
  CPAC/pipeline/plugins/multiproc.py
  CPAC/pipeline/test/test_cpac_pipeline.py
  CPAC/pipeline/test/test_nipype_pipeline_engine.py
  dev/docker_data/run.py
Labels: bug, Hacktoberfest, develop

#1592 Phase-Difference field map ingress/parsing fixes
  CHANGELOG.md
  CPAC/distortion_correction/distortion_correction.py
  CPAC/info.py
  CPAC/registration/registration.py
  CPAC/utils/datasource.py
  dev/docker_data/run.py
Labels: bug

#1610 ✨ Add commandline flags for scan inclusion
  .circleci/main.yml
  CHANGELOG.md
  CPAC/anat_preproc/anat_preproc.py
  CPAC/func_preproc/func_preproc.py
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/test/issue_1606_data_config.yml
  CPAC/pipeline/test/sample_data.py
  CPAC/registration/registration.py
  CPAC/resources/configs/pipeline_config_monkey-ABCD.yml
  CPAC/resources/cpac_templates.csv
  CPAC/seg_preproc/seg_preproc.py
  CPAC/utils/__init__.py
  CPAC/utils/bids_utils.py
  CPAC/utils/tests/test_bids_utils.py
  CPAC/utils/utils.py
  dev/circleci_data/test_in_image.sh
  dev/docker_data/bids_utils.py
  dev/docker_data/run.py
Labels: feature, improvement
