Repository FCP-INDI/C-PAC, pull requests merged in 2022-10, with the labels that each got.

#1781 🐛 Fix `FUGUE --dwell` parameterization
  .pylintrc
  CHANGELOG.md
  CPAC/distortion_correction/distortion_correction.py
  CPAC/func_preproc/func_ingress.py
  CPAC/image_utils/__init__.py
  CPAC/image_utils/spatial_smoothing.py
  CPAC/image_utils/statistical_transforms.py
  CPAC/longitudinal_pipeline/longitudinal_workflow.py
  CPAC/nuisance/nuisance.py
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/engine.py
  CPAC/pipeline/schema.py
  CPAC/qc/tests/test_qc.py
  CPAC/randomise/randomise.py
  CPAC/registration/registration.py
  CPAC/registration/tests/mocks.py
  CPAC/utils/__init__.py
  CPAC/utils/datasource.py
  CPAC/utils/strategy.py
  CPAC/utils/test_mocks.py
  CPAC/utils/utils.py
  CPAC/utils/yaml_template.py
Labels: bug, 2 - High Priority, release, RBC, develop

#1769 Ingress and use TotalReadoutTime from epi fmap meta-data in FSL topup
  CHANGELOG.md
  CPAC/distortion_correction/distortion_correction.py
  CPAC/distortion_correction/utils.py
  CPAC/utils/build_data_config.py
  CPAC/utils/datasource.py
Labels: RBC

#1778 🚚 Move C-PAC generated configs into `log/sub-${sub}_ses-${ses}` subdirectory
  .pylintrc
  CPAC/pipeline/__init__.py
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/cpac_runner.py
  CPAC/pipeline/random_state/seed.py
  CPAC/utils/__init__.py
  CPAC/utils/configuration/__init__.py
  CPAC/utils/configuration/configuration.py
  dev/docker_data/run.py
Labels: RBC, enhancement

#1803 💚 Fix CI build: Upgrade miniconda (4.8.2 → 4.12.0)
  .github/Dockerfiles/Ubuntu.bionic-non-free.Dockerfile
  .github/Dockerfiles/Ubuntu.xenial-20200114.Dockerfile
  .github/scripts/get_package_id.py
  .github/workflows/build_stages.yml
  CPAC/info.py
  requirements.txt
Labels: 2 - High Priority, devops

#1802 ✏️ Fix typo (octal, not hexadecimal)
  dev/docker_data/run.py
Labels: bug, develop

#1804 🩹 Distortion correction: ~~el~~if
  CPAC/distortion_correction/utils.py
  CPAC/resources/configs/pipeline_config_abcd-options.yml
  CPAC/resources/configs/pipeline_config_anat-only.yml
  CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml
  CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml
  CPAC/resources/configs/pipeline_config_ccs-options.yml
  CPAC/resources/configs/pipeline_config_ndmg.yml
  CPAC/resources/configs/pipeline_config_rbc-options.yml
  CPAC/resources/configs/pipeline_config_regtest-1.yml
  CPAC/resources/configs/pipeline_config_regtest-2.yml
  CPAC/resources/configs/pipeline_config_regtest-3.yml
  CPAC/resources/configs/pipeline_config_regtest-4.yml
Labels: RBC, develop

#1809 🔥 Remove deprecated `--disable_file_logging` CLI flag
  CHANGELOG.md
  CPAC/resources/configs/pipeline_config_anat-only.yml
  CPAC/resources/configs/pipeline_config_rbc-options.yml
  CPAC/utils/configuration/yaml_template.py
  dev/docker_data/run.py
Labels: bug, develop
