Repository FCP-INDI/C-PAC, pull requests merged in 2022-11, with the labels that each got.

#1818 🔧 rbc-options: Turn on f/alff, lfcd, binarized degree centrality
  CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml
  CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml
  CPAC/resources/configs/pipeline_config_blank.yml
  CPAC/resources/configs/pipeline_config_rbc-options.yml
  CPAC/resources/configs/pipeline_config_regtest-1.yml
  CPAC/resources/configs/pipeline_config_regtest-2.yml
  CPAC/resources/configs/pipeline_config_regtest-3.yml
  CPAC/resources/configs/pipeline_config_regtest-4.yml
Labels: RBC

#1819 space-template renaming in output directory write-out
  CHANGELOG.md
  CPAC/network_centrality/pipeline.py
  CPAC/pipeline/engine.py
  CPAC/pipeline/schema.py
  CPAC/registration/registration.py
  CPAC/resources/configs/pipeline_config_blank.yml
  CPAC/resources/configs/pipeline_config_default.yml
  CPAC/resources/cpac_templates.csv
  CPAC/resources/templates/BIDS_identifiers.tsv
  CPAC/resources/templates/__init__.py
  CPAC/resources/templates/lookup_table.py
  CPAC/utils/utils.py
Labels: RBC

#1824 👔 Update some pipeline plumbing to allow updated rbc-options' derivatives
  CPAC/alff/alff.py
  CPAC/nuisance/nuisance.py
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/schema.py
  CPAC/registration/registration.py
  CPAC/reho/reho.py
  CPAC/resources/configs/pipeline_config_rbc-options.yml
Labels: RBC, develop

#1830 🥅 Update expected outputs check to match updated derivatives structure
  CPAC/pipeline/check_outputs.py
  CPAC/pipeline/engine.py
  CPAC/utils/__init__.py
Labels: bug, develop

#1822 👷 Reduce CI workflow duplication
  .github/workflows/check_updated_preconfigs.yml
Labels: devops, RBC

#1825 🎨 Change `-`s in BIDS values to camelCase
  CPAC/utils/utils.py
Labels: BIDS, RBC

#1828 🥅 Set exit code to 1 if graph build fails
  .github/workflows/build_stages.yml
  CPAC/pipeline/cpac_runner.py
  dev/docker_data/run.py
Labels: RBC

#1829 🐛 Bug fixes identified during regression test for v1.8.5
  CPAC/func_preproc/func_preproc.py
  CPAC/nuisance/nuisance.py
  CPAC/pipeline/check_outputs.py
  CPAC/pipeline/engine.py
  CPAC/registration/registration.py
  CPAC/utils/__init__.py
Labels: bug, develop

#1831 🚚 Replace integers suffixes with descriptive strings for regressor forks
  CHANGELOG.md
  CPAC/pipeline/engine.py
  CPAC/utils/bids_utils.py
  CPAC/utils/utils.py
Labels: RBC

#1833 🎨 Add template specification to new outputs from #1820
  CPAC/qc/xcp.py
  CPAC/registration/registration.py
Labels: RBC, develop

#1834 🎨 Add missing empty cells in `cpac_outputs.tsv`
  CPAC/resources/cpac_outputs.tsv
Labels: develop

#1832 🚚 Rename `motion-derivatives` to `desc-motionDerivatives_motion`
  CPAC/utils/outputs.py
  CPAC/utils/utils.py
Labels: RBC, enhancement

#1836 🐛 Some crashes identified during regression testing of v1.8.5
  CPAC/network_centrality/network_centrality.py
  CPAC/network_centrality/utils.py
  CPAC/pipeline/schema.py
  CPAC/resources/configs/pipeline_config_abcd-options.yml
  CPAC/utils/utils.py
Labels: bug, develop

#1837 👔 Fork on `motion_estimate_filter.filters`
  CHANGELOG.md
  CPAC/func_preproc/func_preproc.py
  CPAC/pipeline/engine.py
  CPAC/pipeline/schema.py
  CPAC/pipeline/test/test_schema_validation.py
  CPAC/resources/configs/pipeline_config_blank.yml
  CPAC/resources/configs/pipeline_config_default.yml
  CPAC/surface/__init__.py
  CPAC/utils/bids_utils.py
Labels: engine, BIDS, enhancement

#1842 ✅ Smoke tests: Fix failing
  .github/workflows/smoke_test_participant.yml
  CPAC/anat_preproc/anat_preproc.py
  CPAC/registration/registration.py
  CPAC/resources/configs/pipeline_config_blank.yml
  CPAC/resources/configs/pipeline_config_monkey-ABCD.yml
  CPAC/resources/configs/pipeline_config_regtest-3.yml
  CPAC/resources/configs/pipeline_config_regtest-4.yml
  CPAC/resources/configs/pipeline_config_rodent.yml
Labels: devops, testing

#1844 🐛 Fix expected outputs check to better find outputs
  CPAC/pipeline/check_outputs.py
  CPAC/resources/configs/pipeline_config_abcd-options.yml
  CPAC/utils/bids_utils.py
Labels: bug, develop

#1845 🔧 Make `desc-reorient_T1w` a debugging output
  CPAC/resources/cpac_outputs.tsv
Labels: user-reported

#1847 🐛 Restore `freesurfer_dir` ingress from pipeline config
  CHANGELOG.md
  CPAC/pipeline/engine.py
Labels: bug
