Repository FCP-INDI/C-PAC, pull requests merged in 2022-06, with the labels that each got.

#1716 👽️ Replace `optparse` with `click`
  CHANGELOG.md
  CPAC/unet/function.py
  CPAC/utils/configuration.py
  CPAC/utils/utils.py
  CPAC/utils/yaml_template.py
Labels: devops, dependencies, python

#1717 💄 Initialize pylint config
  .pylintrc
  CHANGELOG.md
  CPAC/pipeline/cpac_pipeline.py
  CPAC/utils/utils.py
Labels: devops, improvement, docs, python, style, NMIND

#1718 🐛 Allow tracking opt-out for config util
  CHANGELOG.md
  CPAC/__main__.py
Labels: bug, devops, improvement

#1733 🎨 SSOT options for `get_motion_refs` NodeBlock
  CPAC/func_preproc/func_preproc.py
  CPAC/pipeline/engine.py
  CPAC/utils/docs.py
  CPAC/utils/tests/test_utils.py
Labels: 0 - Low Priority, docs, enhancement

#1734 📝 List available preconfigs in usage string
  CHANGELOG.md
  CPAC/pipeline/__init__.py
  CPAC/utils/docs.py
  CPAC/utils/utils.py
  dev/docker_data/run.py
Labels: docs, enhancement

#1748 Updated the monkey preconfig to use local segmentation atlases
  CPAC/resources/configs/pipeline_config_monkey.yml
Labels: NHP

#1737 🐛 RBC updates: Switch to MNI2006 templates & CBIG's Schaefer; fix XCP-QC 'final' values
  .github/workflows/build_stages.yml
  CHANGELOG.md
  CPAC/func_preproc/func_preproc.py
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/schema.py
  CPAC/qc/xcp.py
  CPAC/resources/configs/pipeline_config_fmriprep-options.yml
  CPAC/resources/configs/pipeline_config_rbc-options.yml
  CPAC/resources/cpac_outputs.tsv
  CPAC/resources/cpac_templates.csv
  CPAC/utils/monitoring/custom_logging.py
  dev/docker_data/default_pipeline.yml
Labels: RBC
