Repository FCP-INDI/C-PAC, pull requests merged in 2022-09, with the labels that each got.

#1773 /Fix/assign_stopidx_asend
  CPAC/func_preproc/func_preproc.py
  CPAC/pipeline/schema.py
Labels: bug, support, user-reported

#1764 🔖 Hotfix: Update version to 1.8.4
  CPAC/pipeline/engine.py
  CPAC/resources/configs/data_config_S3-BIDS-ABIDE.yml
  CPAC/resources/configs/data_config_S3-BIDS-ADHD200.yml
  CPAC/resources/configs/data_config_S3-BIDS-ADHD200_only2.yml
  CPAC/resources/configs/data_config_S3-BIDS-NKI-RocklandSample.yml
  CPAC/resources/configs/data_config_cpac_benchmark.yml
  CPAC/resources/configs/data_settings_template.yml
  CPAC/resources/configs/group_config_template.yml
  CPAC/resources/configs/pipeline_config_abcd-options.yml
  CPAC/resources/configs/pipeline_config_anat-only.yml
  CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml
  CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml
  CPAC/resources/configs/pipeline_config_blank.yml
  CPAC/resources/configs/pipeline_config_ccs-options.yml
  CPAC/resources/configs/pipeline_config_fmriprep-options.yml
  CPAC/resources/configs/pipeline_config_fx-options.yml
  CPAC/resources/configs/pipeline_config_monkey-ABCD.yml
  CPAC/resources/configs/pipeline_config_monkey.yml
  CPAC/resources/configs/pipeline_config_ndmg.yml
  CPAC/resources/configs/pipeline_config_nhp-macaque.yml
  CPAC/resources/configs/pipeline_config_preproc.yml
  CPAC/resources/configs/pipeline_config_rbc-options.yml
  CPAC/resources/configs/pipeline_config_regtest-1.yml
  CPAC/resources/configs/pipeline_config_regtest-2.yml
  CPAC/resources/configs/pipeline_config_regtest-3.yml
  CPAC/resources/configs/pipeline_config_regtest-4.yml
  CPAC/resources/configs/pipeline_config_rodent.yml
  CPAC/resources/configs/system_config.yml
  CPAC/resources/configs/test_configs/data-test_S3-ADHD200_1.yml
  CPAC/resources/configs/test_configs/data-test_S3-ADHD200_no-params.yml
  CPAC/resources/configs/test_configs/data-test_S3-NKI-RS_fmap.yml
  CPAC/resources/configs/test_configs/data_config_S3_CoRR_5only_mult-scan.yml
  CPAC/resources/configs/test_configs/data_config_S3_CoRR_5only_mult-sess.yml
  CPAC/resources/configs/test_configs/pipe-test_ABCD.yml
  CPAC/resources/configs/test_configs/pipe-test_ANTs-3dSk-AllNuis.yml
  CPAC/resources/configs/test_configs/pipe-test_ANTs-3dSk-DistCorr3dSk.yml
  CPAC/resources/configs/test_configs/pipe-test_ANTs-3dSk-DistCorrBET.yml
  CPAC/resources/configs/test_configs/pipe-test_ANTs-BET-AllNuis.yml
  CPAC/resources/configs/test_configs/pipe-test_FNIRT-3dSk-AllNuis.yml
  CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis-BASC.yml
  CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis-ISC-voxel.yml
  CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis-ISC.yml
  CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis-MDMR.yml
  CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis.yml
  CPAC/resources/configs/test_configs/pipe-test_all.yml
  README.md
  dev/docker_data/default_pipeline.yml
Labels: bug, devops, release, user-reported, hotfix

#1761 👔 RBC update: Apply nuisance regression in template space
  .github/Dockerfiles/C-PAC.develop-ABCD-HCP-bionic.Dockerfile
  .github/Dockerfiles/C-PAC.develop-bionic.Dockerfile
  .github/Dockerfiles/C-PAC.develop-fMRIPrep-LTS-xenial.Dockerfile
  .github/workflows/check_updated_version.yml
  .gitignore
  .pylintrc
  CHANGELOG.md
  CPAC/connectome/connectivity_matrix.py
  CPAC/func_preproc/func_preproc.py
  CPAC/nuisance/nuisance.py
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/cpac_runner.py
  CPAC/pipeline/engine.py
  CPAC/pipeline/schema.py
  CPAC/pipeline/test/test_cpac_runner.py
  CPAC/pipeline/test/test_engine.py
  CPAC/qc/xcp.py
  CPAC/registration/registration.py
  CPAC/resources/configs/pipeline_config_blank.yml
  CPAC/resources/configs/pipeline_config_default.yml
  CPAC/resources/configs/pipeline_config_fmriprep-options.yml
  CPAC/resources/configs/pipeline_config_monkey-ABCD.yml
  CPAC/resources/configs/pipeline_config_rbc-options.yml
  CPAC/utils/__init__.py
  CPAC/utils/build_data_config.py
  CPAC/utils/configuration/__init__.py
  CPAC/utils/configuration/configuration.py
  CPAC/utils/configuration/diff.py
  CPAC/utils/datatypes.py
  CPAC/utils/docs.py
  CPAC/utils/monitoring/__init__.py
  CPAC/utils/monitoring/custom_logging.py
  CPAC/utils/tests/test_yaml.py
  CPAC/utils/utils.py
  CPAC/utils/yaml_template.py
  Dockerfile
  dev/circleci_data/override_version_tag_list
  dev/docker_data/run.py
  setup.py
  variant-ABCD-HCP.Dockerfile
  variant-fMRIPrep-LTS.Dockerfile
Labels: RBC

#1775 🚚 Use `f'pipeline_{pipeline_name}'` subdirectories for `log`, `working`, and `output`
  CHANGELOG.md
  CPAC/info.py
  CPAC/longitudinal_pipeline/longitudinal_workflow.py
  CPAC/pipeline/check_outputs.py
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/engine.py
  CPAC/pipeline/schema.py
  CPAC/pipeline/test/test_schema_validation.py
  CPAC/resources/configs/pipeline_config_default.yml
  requirements.txt
Labels: bug, 2 - High Priority, improvement, RBC

#1777 🐛 Differentiate sametime data and pipeline configs
  CHANGELOG.md
  CPAC/utils/yaml_template.py
Labels: RBC
