Repository FCP-INDI/C-PAC, pull requests merged in 2023-06, with the labels that each got.

#1899 NodeBlock decorators
  CPAC/alff/alff.py
  CPAC/anat_preproc/anat_preproc.py
  CPAC/distortion_correction/distortion_correction.py
  CPAC/func_preproc/func_preproc.py
  CPAC/longitudinal_pipeline/longitudinal_workflow.py
  CPAC/network_centrality/pipeline.py
  CPAC/nuisance/nuisance.py
  CPAC/pipeline/engine.py
  CPAC/pipeline/nodeblock.py
  CPAC/qc/pipeline.py
  CPAC/qc/xcp.py
  CPAC/registration/registration.py
  CPAC/reho/reho.py
  CPAC/sca/sca.py
  CPAC/seg_preproc/seg_preproc.py
  CPAC/surface/surf_preproc.py
  CPAC/timeseries/timeseries_analysis.py
  CPAC/utils/docs.py
  CPAC/utils/tests/test_utils.py
  CPAC/vmhc/vmhc.py
Labels: OHBM 2023

#1905 Don't check system dependencies with test_config
  CPAC/pipeline/cpac_pipeline.py
Labels: enhancement

#1958 👽 Update CLI to accept dashes and underscores where appropriate
  CHANGELOG.md
  CPAC/__main__.py
  CPAC/info.py
  CPAC/utils/versioning/dependencies.py
  dev/circleci_data/test_external_utils.py
  dev/docker_data/run.py
  requirements.txt
Labels: 2 - High Priority
