Repository FCP-INDI/C-PAC, pull requests merged in 2023-10, with the labels that each got.

#1999 📦️ Restore `WORKDIR` to final-stage Dockerfiles
  .github/Dockerfiles/C-PAC.develop-ABCD-HCP-bionic.Dockerfile
  .github/Dockerfiles/C-PAC.develop-fMRIPrep-LTS-xenial.Dockerfile
  .github/Dockerfiles/C-PAC.develop-jammy.Dockerfile
  .github/Dockerfiles/C-PAC.develop-lite-jammy.Dockerfile
Labels: devops, develop

#1989 👔 Use filtered motion parameters in nuisance regression
  CHANGELOG.md
  CPAC/func_preproc/func_motion.py
  CPAC/nuisance/nuisance.py
  CPAC/pipeline/engine.py
  CPAC/pipeline/utils.py
  CPAC/qc/pipeline.py
  CPAC/qc/xcp.py
  CPAC/resources/cpac_outputs.tsv
  CPAC/utils/configuration/__init__.py
  CPAC/utils/configuration/configuration.py
  CPAC/utils/configuration/diff.py
  CPAC/utils/configuration/yaml_template.py
  CPAC/utils/typing.py
  CPAC/utils/utils.py
Labels: feature

#1624 All motion params
  CPAC/anat_preproc/anat_preproc.py
  CPAC/aroma/aroma.py
  CPAC/func_preproc/func_motion.py
  CPAC/func_preproc/func_preproc.py
  CPAC/generate_motion_statistics/generate_motion_statistics.py
  CPAC/generate_motion_statistics/utils.py
  CPAC/nuisance/nuisance.py
  CPAC/pipeline/cpac_pipeline.py
  CPAC/pipeline/engine.py
  CPAC/qc/pipeline.py
  CPAC/qc/utils.py
  CPAC/qc/xcp.py
  CPAC/registration/registration.py
  CPAC/resources/cpac_outputs.tsv
  CPAC/utils/build_data_config.py
  CPAC/utils/interfaces/function/function.py
  CPAC/utils/outputs.py
  CPAC/utils/utils.py
Labels: BIDS, enhancement
