Repository FCP-INDI/C-PAC, pull requests merged in 2025-03, with the labels that each got.

#2195 👽️ Update Dockerfile `LABEL`s re: deprecated `LegacyKeyValueFormat`
  .github/Dockerfiles/AFNI.23.3.09-jammy.Dockerfile
  .github/Dockerfiles/ANTs.2.4.3-jammy.Dockerfile
  .github/Dockerfiles/C-PAC.develop-jammy.Dockerfile
  .github/Dockerfiles/C-PAC.develop-lite-jammy.Dockerfile
  .github/Dockerfiles/FSL.6.0.6.5-jammy.Dockerfile
  .github/Dockerfiles/FSL.data.Dockerfile
  .github/Dockerfiles/FreeSurfer.6.0.0-min.neurodocker-jammy.Dockerfile
  .github/Dockerfiles/ICA-AROMA.0.4.4-beta-jammy.Dockerfile
  .github/Dockerfiles/Ubuntu.jammy-non-free.Dockerfile
  .github/Dockerfiles/base-lite.Dockerfile
  .github/Dockerfiles/base-standard.Dockerfile
  .github/Dockerfiles/c3d.1.0.0-jammy.Dockerfile
  .github/Dockerfiles/connectome-workbench.1.5.0.neurodebian-jammy.Dockerfile
  .github/Dockerfiles/neuroparc.1.0-human-bionic.Dockerfile
  Dockerfile
  variant-lite.Dockerfile
Labels: devops

#2197 🔒️👽️👷➖ Remove `tj-actions/changed-files` dependency
  .github/workflows/on_push.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: 3 - Critical, devops

#2181 Spike Regression connection fix
  CHANGELOG.md
  CPAC/nuisance/nuisance.py
  CPAC/nuisance/utils/utils.py
  CPAC/pipeline/schema.py
Labels: bug
